### PR TITLE
add lead.id, outcome and reason to response variables for all

### PR DESCRIPTION
**Pull request by zalary**
integrations.

resolves issue #1

### CODE REVIEW

**Comment by alexkwolfe** [comment]
Rather than duplicating these response variables across each different integration (note, person, tag), consider using the same strategy that the request variables use: concatenate the base variables to the specific integration variables.

**Comment by zalary** [comment]
Maybe I don't understand, but wouldn't that lead to multiple steps having a single outcome?  What would happen if the base request was okay but adding a person failed?

**Comment by alexkwolfe** [comment]
I'm not sure I follow. Look at this code:

https://github.com/activeprospect/leadconduit-integration-highrise/blob/546380dcbd03351adba371d2ba5eea864509de9d/src/note.coffee#L21-L27

The purpose of `base.request.variables().concat(vars)` is to grab the common request variables from the base definition rather than redeclare them here. This centralizes the definition of all request variables in `base.coffee` (DRY and all that). Alas, this is the entire purpose of `base.coffee`: to define in a single  place all the things that are common across the various Highrise endpoints.

**Comment by zalary** [comment]
So, in the base request example, I get that it centralizes the common things.  And while `lead.id` certainly is a common response variable, I'm not sure if `outcome` and `reason` are common or not, or if putting them would result it them being the same across each one, even if the actually outcome for each was different.

It's possible I'm just not clue-ing correctly on how this is working.

**Comment by alexkwolfe** [comment]
All integrations are supposed to give an `outcome` and `reason` in their response variables. That's the change you are making in this PR. The only question is, are you going to define that in 4 different files, or just one?

**Comment by alexkwolfe** [comment]
Also, I'm not sure why I said to add `lead.id`. I think the existing `id` is sufficient.

**Pull request closed without merging**
